travis:
  secure:
    BINSTAR_TOKEN: ffeR95Tlfh16EnmlLINon6otOP75EpesmjMwA2w+dkPeRU3TjlcJH0Ulg1CKK01IC1zXv25nB/9cuA8CwBIGa2GsXyEXNU7BwcYj7CaHfSBXmUgGKrwFJUBzGZ1xzyFTBllebtyZYCcuiYz7aJBNjQFjBxZCWSl34GywBnFmUj5qotrccKAGSqhGVIb2yfamzbWeNqspUp5oHEMTfNPliWZOTZqwy3ML3i1PvHqBPRX/JKk9JcSceIL2eg2PCvU/Q2sN1cDzvLcWfTmyd6y6mL43mhlyFwer1Lv/Tx1MlIegAx0hx51qC0QkWm9KxmaPygRI8RAu24zPCkZPphz+gmmAGq3bpTguiriE1I3U5ZWAmHzc8qruZZMkh7kbieFw+lFkX2XJZbVOElqIXSvIWl7dyIkwcnMPFW/5qXKdcCPtZspmu1Z5Rzlp9iCvSJaf44Nxg7s5d2kKsTfVCqNEQEHdhyLHqnBOKw9Na/zGALJ7JVtw/RZB1O9gFsmEFXlm6+9qGoTz4gsYwOssaqNAVq+T5DzChUm6Xad0YPApe8V5rAS74614D9KD7PHkp/Fz4xEKkfy54clzZAubppsetKnHSor6lPLREPM9izNleUgbbxL04OkTrQomha0rGdf5cdxVoBdVXSJNdF+QNznUzZnwZI1Oi67sAGJG0P5Zjdo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
